### ISSUE TITLE
Crash with modular.datomic/DatomicConnection

### ISSUE THREAD

**Issue by blazeroot** [milesian/BigBang#1]
Hi, I'm trying to get system-diagrams work in my project but I faced problem that I'm not sure how to resolve. I'm using modular.datomic and have connection component which returns datomic connection after start (https://github.com/juxt/modular/blob/master/modules/datomic/src/modular/datomic.clj#L42-L45). So far system was working fine, but after trying to start it using:

``` clojure
(defn start
  "Starts the current development system."
  []
  (alter-var-root #'system #(bigbang/expand % {:before-start [[identity/add-meta-key %]
                                                              [identity/assoc-meta-who-to-deps]]
                                               :after-start [[aop/wrap diagram]]})))
```

I'm getting this:

``` clojure
dev=> (go)

ClassCastException datomic.peer.LocalConnection cannot be cast to clojure.lang.IObj  clojure.core/with-meta (core.clj:214)
dev=> (use 'clojure.stacktrace)
nil
dev=> (print-stack-trace *e)
clojure.lang.ExceptionInfo: Error in component :players-resource in system com.stuartsierra.component.SystemMap calling milesian.bigbang$expand$bigbang_start__15815@f2eb6bd
 at clojure.core$ex_info.invoke (core.clj:4403)
    com.stuartsierra.component$try_action.invoke (component.clj:101)
    com.stuartsierra.component$update_system$fn__6547.invoke (component.clj:125)
    clojure.core.protocols/fn (protocols.clj:127)
    clojure.core.protocols$fn__6057$G__6052__6066.invoke (protocols.clj:19)
    clojure.core.protocols$seq_reduce.invoke (protocols.clj:31)
    clojure.core.protocols/fn (protocols.clj:48)
    clojure.core.protocols$fn__6031$G__6026__6044.invoke (protocols.clj:13)
    clojure.core$reduce.invoke (core.clj:6289)
    com.stuartsierra.component$update_system.doInvoke (component.clj:129)
    clojure.lang.RestFn.invoke (RestFn.java:445)
    milesian.bigbang$expand.invoke (bigbang.clj:12)
    dev$start$fn__16763.invoke (dev.clj:82)
    clojure.lang.AFn.applyToHelper (AFn.java:154)
    clojure.lang.AFn.applyTo (AFn.java:144)
    clojure.lang.Var.alterRoot (Var.java:303)
    clojure.core$alter_var_root.doInvoke (core.clj:5052)
    clojure.lang.RestFn.invoke (RestFn.java:425)
    dev$start.invoke (dev.clj:82)
    dev$go.invoke (dev.clj:96)
    dev$eval16773.invoke (form-init7483327959407940928.clj:1)
    clojure.lang.Compiler.eval (Compiler.java:6703)
    clojure.lang.Compiler.eval (Compiler.java:6666)
    clojure.core$eval.invoke (core.clj:2927)
    clojure.main$repl$read_eval_print__6625$fn__6628.invoke (main.clj:239)
    clojure.main$repl$read_eval_print__6625.invoke (main.clj:239)
    clojure.main$repl$fn__6634.invoke (main.clj:257)
    clojure.main$repl.doInvoke (main.clj:257)
    clojure.lang.RestFn.invoke (RestFn.java:1523)
    clojure.tools.nrepl.middleware.interruptible_eval$evaluate$fn__897.invoke (interruptible_eval.clj:67)
    clojure.lang.AFn.applyToHelper (AFn.java:152)
    clojure.lang.AFn.applyTo (AFn.java:144)
    clojure.core$apply.invoke (core.clj:624)
    clojure.core$with_bindings_STAR_.doInvoke (core.clj:1862)
    clojure.lang.RestFn.invoke (RestFn.java:425)
    clojure.tools.nrepl.middleware.interruptible_eval$evaluate.invoke (interruptible_eval.clj:51)
    clojure.tools.nrepl.middleware.interruptible_eval$interruptible_eval$fn__939$fn__942.invoke (interruptible_eval.clj:183)
    clojure.tools.nrepl.middleware.interruptible_eval$run_next$fn__932.invoke (interruptible_eval.clj:152)
    clojure.lang.AFn.run (AFn.java:22)
    java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1142)
    java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:617)
    java.lang.Thread.run (Thread.java:745)
nil
```

If I understand correctly, the problem is `datomic.peer.LocalConnection` isn't a component (record?). Am I right? Am I doing something wrong here or it's a bug in BigBang?

**Comment by tangrammer** [comment]
Hi @blazeroot,
I think that modular/datomic [component](https://github.com/juxt/modular/blob/master/modules/datomic/src/modular/datomic.clj#L42-L45) should return `this` instead of datomic connection following stuartsierra/component examples or even other modules of juxt/modular. I'm going to open an issue in modular to know the reasons of this datomic component return value.
Anyway I'll fix my aop/wrap fn to ensure that is a record the returned value of component/start

Thanks a lot!
Juan

**Comment by tangrammer** [comment]
I added some checks for that in tangrammer/co-dependency and milesian/identity that fix this special component/start return values 
you'll need to use now following versions [milesian/identity "0.1.4-SNAPSHOT"] and (only in case that you are currently using co-dependency) [tangrammer/co-dependency "0.1.6-SNAPSHOT"]

Please check that it fix your error and feel free to close this issue after that

Thanks again!
Juan

**Comment by blazeroot** [comment]
Thanks @tangrammer for quick fix! Unfortunately I still got this error

``` clojure
dev=> (go)
ClassCastException datomic.peer.LocalConnection cannot be cast to clojure.lang.IObj  clojure.core/with-meta (core.clj:214)
dev=> (use 'clojure.stacktrace)
nil
dev=> (print-stack-trace *e)
clojure.lang.ExceptionInfo: Error in component :players-resource in system com.stuartsierra.component.SystemMap calling milesian.bigbang$expand$bigbang_start__15815@6da730e2
 at clojure.core$ex_info.invoke (core.clj:4403)
    com.stuartsierra.component$try_action.invoke (component.clj:101)
    com.stuartsierra.component$update_system$fn__6547.invoke (component.clj:125)
    clojure.core.protocols/fn (protocols.clj:127)
    clojure.core.protocols$fn__6057$G__6052__6066.invoke (protocols.clj:19)
    clojure.core.protocols$seq_reduce.invoke (protocols.clj:31)
    clojure.core.protocols/fn (protocols.clj:48)
    clojure.core.protocols$fn__6031$G__6026__6044.invoke (protocols.clj:13)
    clojure.core$reduce.invoke (core.clj:6289)
    com.stuartsierra.component$update_system.doInvoke (component.clj:129)
    clojure.lang.RestFn.invoke (RestFn.java:445)
    milesian.bigbang$expand.invoke (bigbang.clj:12)
    dev$start$fn__16764.invoke (dev.clj:82)
    clojure.lang.AFn.applyToHelper (AFn.java:154)
    clojure.lang.AFn.applyTo (AFn.java:144)
    clojure.lang.Var.alterRoot (Var.java:303)
    clojure.core$alter_var_root.doInvoke (core.clj:5052)
    clojure.lang.RestFn.invoke (RestFn.java:425)
    dev$start.invoke (dev.clj:82)
    dev$go.invoke (dev.clj:96)
    dev$eval16774.invoke (form-init2886145229305305506.clj:1)
    clojure.lang.Compiler.eval (Compiler.java:6703)
    clojure.lang.Compiler.eval (Compiler.java:6666)
    clojure.core$eval.invoke (core.clj:2927)
    clojure.main$repl$read_eval_print__6625$fn__6628.invoke (main.clj:239)
    clojure.main$repl$read_eval_print__6625.invoke (main.clj:239)
    clojure.main$repl$fn__6634.invoke (main.clj:257)
    clojure.main$repl.doInvoke (main.clj:257)
    clojure.lang.RestFn.invoke (RestFn.java:1523)
    clojure.tools.nrepl.middleware.interruptible_eval$evaluate$fn__897.invoke (interruptible_eval.clj:67)
    clojure.lang.AFn.applyToHelper (AFn.java:152)
    clojure.lang.AFn.applyTo (AFn.java:144)
    clojure.core$apply.invoke (core.clj:624)
    clojure.core$with_bindings_STAR_.doInvoke (core.clj:1862)
    clojure.lang.RestFn.invoke (RestFn.java:425)
    clojure.tools.nrepl.middleware.interruptible_eval$evaluate.invoke (interruptible_eval.clj:51)
    clojure.tools.nrepl.middleware.interruptible_eval$interruptible_eval$fn__939$fn__942.invoke (interruptible_eval.clj:183)
    clojure.tools.nrepl.middleware.interruptible_eval$run_next$fn__932.invoke (interruptible_eval.clj:152)
    clojure.lang.AFn.run (AFn.java:22)
    java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1142)
    java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:617)
    java.lang.Thread.run (Thread.java:745)
nil
```

part of `project.cjs`

``` clojure
:dependencies [

             ...

             ;; COMPONENTS
             [com.stuartsierra/component "0.2.2"]
             [tangrammer/co-dependency "0.1.6-SNAPSHOT"]

             ...

:profiles {:dev {:dependencies [[org.clojure/tools.namespace "0.2.5"]
                                            [spyscope "0.1.5"]

                                            ;; FOR DIAGRAMS
                                            [milesian/system-diagrams "0.1.2"]
                                            [milesian/bigbang "0.1.1"]
                                            [milesian/aop "0.1.4"]
                                            [milesian/identity "0.1.4-SNAPSHOT"]]
```

It's the same exception (err diff https://www.diffchecker.com/589j74fh).

I'll create my own valid connection component and check if that works.

**Comment by tangrammer** [comment]
Thanks @blazeroot for your feedback

it's a bit weird because your configuration works fine to me 
I leave you here a demo project using last milesian snapshots maybe it helps you 
https://github.com/tangrammer/modular-cylon-example/tree/milesian-bug
branch: milesian-bug

cheers
Juan

**Comment by blazeroot** [comment]
Thanks @tangrammer! I'll definitely compare it later today!

**Comment by tvanhens** [comment]
@blazeroot did you figure out what the underlying issue was? I am experiencing the same problem and I haven't been able to track it down.

**Comment by blazeroot** [comment]
@tvanhens sth went wrong on my side with deps and I was running `0.1.3` instead of `0.1.4-SNAPSHOT` as declared in `project.clj`. When I started to compare my code with modular-cylon-example and run my code again (and it loaded `0.1.4-SNAPSHOT`) I didn't get that exception anymore.

**Comment by tvanhens** [comment]
Looks like rerunning lein deps with 0.1.4-SNAPSHOT got me a bit further but running into a different error when running (dev/reset):

clojure.lang.ExceptionInfo: Error in component :authorization-server-webrouter in system com.stuartsierra.component.SystemMap calling milesian.bigbang$expand$bigbang_start__15785@1f665b32
 at clojure.core$ex_info.invoke (core.clj:4566)
    com.stuartsierra.component$try_action.invoke (component.clj:101)
    com.stuartsierra.component$update_system$fn__2276.invoke (component.clj:125)
    clojure.core.protocols/fn (protocols.clj:132)
    clojure.core.protocols$fn__6395$G__6390__6404.invoke (protocols.clj:19)
    clojure.core.protocols$seq_reduce.invoke (protocols.clj:31)
    clojure.core.protocols/fn (protocols.clj:53)
    clojure.core.protocols$fn__6369$G__6364__6382.invoke (protocols.clj:13)
    clojure.core$reduce.invoke (core.clj:6461)
    com.stuartsierra.component$update_system.doInvoke (component.clj:129)
    clojure.lang.RestFn.invoke (RestFn.java:445)
    milesian.bigbang$expand.invoke (bigbang.clj:12)
    dev$start$fn__17936.invoke (dev.clj:74)
    clojure.lang.AFn.applyToHelper (AFn.java:154)
    clojure.lang.AFn.applyTo (AFn.java:144)
    clojure.lang.Var.alterRoot (Var.java:303)
    clojure.core$alter_var_root.doInvoke (core.clj:5219)
    clojure.lang.RestFn.invoke (RestFn.java:425)
    dev$start.invoke (dev.clj:74)
    dev$go.invoke (dev.clj:88)
    clojure.lang.Var.invoke (Var.java:375)
    clojure.tools.namespace.repl$do_refresh.invoke (repl.clj:99)
    clojure.tools.namespace.repl$refresh.doInvoke (repl.clj:142)
    clojure.lang.RestFn.invoke (RestFn.java:421)
    dev$reset.invoke (dev.clj:94)
    dev$eval16572.invoke (form-init7823275982163412558.clj:1)
    clojure.lang.Compiler.eval (Compiler.java:6768)
    clojure.lang.Compiler.eval (Compiler.java:6731)
    clojure.core$eval.invoke (core.clj:3076)
    clojure.main$repl$read_eval_print__7020$fn__7023.invoke (main.clj:239)
    clojure.main$repl$read_eval_print__7020.invoke (main.clj:239)
    clojure.main$repl$fn__7029.invoke (main.clj:257)
    clojure.main$repl.doInvoke (main.clj:257)
    clojure.lang.RestFn.invoke (RestFn.java:1096)
    clojure.tools.nrepl.middleware.interruptible_eval$evaluate$fn__896.invoke (interruptible_eval.clj:56)
    clojure.lang.AFn.applyToHelper (AFn.java:152)
    clojure.lang.AFn.applyTo (AFn.java:144)
    clojure.core$apply.invoke (core.clj:626)
    clojure.core$with_bindings_STAR_.doInvoke (core.clj:1864)
    clojure.lang.RestFn.invoke (RestFn.java:425)
    clojure.tools.nrepl.middleware.interruptible_eval$evaluate.invoke (interruptible_eval.clj:41)
    clojure.tools.nrepl.middleware.interruptible_eval$interruptible_eval$fn__937$fn__940.invoke (interruptible_eval.clj:171)
    clojure.core$comp$fn__4458.invoke (core.clj:2433)
    clojure.tools.nrepl.middleware.interruptible_eval$run_next$fn__930.invoke (interruptible_eval.clj:138)
    clojure.lang.AFn.run (AFn.java:22)
    java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1142)
    java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:617)
    java.lang.Thread.run (Thread.java:745)
